### ISSUE TITLE
Mismatch in variable names between dataset and the book

### ISSUE THREAD

**Issue by matt-dray** [dfe-analytical-services/r-training-course#11]
**Problem**: the variables in [the guide](https://dfe-analytical-services.github.io/r-training-course/) don't match the variable names that are read in from [the data source](https://drive.google.com/file/d/0B5-bg4xFFu09dmsxYm8yZGVEdVE/view).

**Example:** the data has the variable `Government Office Region`, which is referred to in the guide as `Government_Office_Region_Name`; it's actually read in as `Government.Office.Region.Name` with `read.csv()` or `Government Office Region Name` with `read.csv()`.

**Solution**: correct throughout the guide.

**Better solution**: do away with spaces in the variable names in the first place; i.e. with the current dataset do `read_csv() %>% janitor::clean_names() %>% readr::write_csv()` and then host this new output file for use in the book instead of the current dataset.

**Comment by TomFranklin** [comment]
Agree with this issue, had difficulty in the london training session with this

**Comment by matt-dray** [comment]
We get around this issue by using the dataset as mentioned in #12. Just need to update the book.
