### ISSUE TITLE
Variable names are too long

### ISSUE THREAD

**Issue by matt-dray** [dfe-analytical-services/r-training-course#12]
**Problem**: `str()` and `dplyr::glimpse()` are demonstrated in the book as ways to quickly view the structure of the dataset, but they're unreadable in the console with the incredibly long names in the dataset.

**Example**: `Average..Mean..Number.of.Days.Lost.to.Teacher.Sickness.Absence..only.Teachers.in.School.Taking.Sickness.Absence`.

**Solution**: retain only the columns of relevance in the dataset and rename longer names to something shorter so that `str()` and `dplyr::glimpse()` can be demonstrated appropriately; this will require a reupload of the data as in issue #11.

**Comment by matt-dray** [comment]
Simplified subsets of the data are now available at [for workforce data](https://gist.github.com/matt-dray/455a3155f5545438f387a10768ae321c) and FTE](https://gist.github.com/matt-dray/cf487a817aad8d6b60c6e7bd2ff93ffb) (both are stored in gists).

The workforce file contains only a handful of the columns in the original file and they're stored with short snake_case names. The FTE file is for demonstrating joins and can be matched using the `urn` column.

**Comment by TomFranklin** [comment]
Would be good to have this dataset used as the one for the whole training book and linked to chapter 2 to load

**Comment by matt-dray** [comment]
Though beware: when you read in these data you need to specify the `na` argument, as in:

```
swfc <- read_csv(
  "swfc_206_headcount.csv",
  na = c("", " ", "NA", "SUPP", "DNS")
)
``` 

This is a good way to introduce the idea of arguments (if it hasn't already been mentioned); the concept of `NA` in R; and the detection of classes from column content. ([See line 89 here](https://github.com/matt-dray/r-training-eyssar/blob/master/180618_training-doc.R).)

**Comment by matt-dray** [comment]
I'm closing this: we've got nicer datasets now (linked above).
