### ISSUE TITLE
Chapter 3 adding good coding practice

### ISSUE THREAD

**Issue by TomFranklin** [dfe-analytical-services/r-training-course#14]
I think it'd be good to do a section on what we see as good coding practice. @adamrobinson361  mentioned yesterday having a good **readme** in each project to give users an idea of what's going on. I agree that's a good idea, but also think we should have some set style of teaching coding. @matt-dray  mentioned a shortcut to add -------'s across code to break sections. Would be good to hear both your thoughts on this one!

**Comment by TomFranklin** [comment]
Would also be good to adopt and stick with one of the cases stated in 3.1. snake_case etc. and to be consistent with it across the tutorial

**Comment by adamrobinson361** [comment]
Referring to the hadley style guide and bringing out some of the key points but also linking to it: http://adv-r.had.co.nz/Style.html
