### ISSUE TITLE
Chapter 4.3 / 5.7 / 5.9 base and tidy operations

### ISSUE THREAD

**Issue by TomFranklin** [dfe-analytical-services/r-training-course#15]
I found in the training session that it would be quite difficult in the 3 hour window to show both base and dplyr options for selecting and filtering data and to avoid confusion opted to go with the tidy option. For the tutorial, a key part of it for me was trying to build confidence in the people learning and I think tidyverse really helps with that and gives beginners an accessible route into R. 

However I would be happy to teach both base and tidy, as I do think there is good value in learning base.

**Comment by matt-dray** [comment]
So we should be 'tidyverse first', but perhaps have a tip box or short chapter later on about 'further programming' or something.

I think [David Robinson gets this right](http://varianceexplained.org/r/teach-tidyverse/).
