### ISSUE TITLE
Data manipulation restricted to one chapter

### ISSUE THREAD

**Issue by TomFranklin** [dfe-analytical-services/r-training-course#16]
I think it'd be helpful for data manipulation to be just kept in one chapter and to include additional functionality such as: 

- recoding variables
- changing variable names
- arranging data

**Comment by matt-dray** [comment]
Yep.

* Recoding: `dplyr::if_else()` and `dplyr::case_when()` would be very useful.
* Variable names: `dplyr::rename()` and `dplyr::select()` were discussed in the recent sessions ([from line 135 here](https://github.com/matt-dray/r-training-eyssar/blob/master/180618_training-doc.R))
* Arranging: `dplyr::arrange()` was discussed in the last session and I think makes most sense in the context of `dplyr::summarise()` ([line 218 here]((https://github.com/matt-dray/r-training-eyssar/blob/master/180618_training-doc.R))) for organising data to find 'the largest x value' or whatever.

What about the `*_at()`, `*_if()` variants of `mutate`, etc? Too much to handle this early on? Maybe put it in a tip box.

**Comment by TomFranklin** [comment]
Yes agree with all the above, to be honest, I've never used `_at()` or `_if()`! I could use a tip with those haha
