### ISSUE TITLE
Confusion with correct link to click to download data

### ISSUE THREAD

**Issue by TomFranklin** [dfe-analytical-services/r-training-course#20]
In the Sheffield session I had difficulties with people downloading the data from the chapter 2 section. Looking at it now, I can see why with 4 hyperlinks asking to click here. Think we could have one button which has a big CSS box around it asking them to download the data (Data that Matt's cleaned ideally!)

**Comment by matt-dray** [comment]
For reference, the 'clean' data i prepared is available from a couple of gists:

* SWFC FTE data https://gist.github.com/matt-dray/cf487a817aad8d6b60c6e7bd2ff93ffb (also at bit.ly/swfc_fte)
* SWFC headcount data for joining: https://gist.github.com/matt-dray/455a3155f5545438f387a10768ae321c (also at bit.ly/swfc_headcount)

Fewer columns, fewer rows, sensible column names.
